/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter_web/material.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData devices_other = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData phone_android = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData web = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cogs = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData article = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData facebook_1 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData github = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData article_alt = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData lightbulb_outline = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData bitbucket = const IconData(0xf171, fontFamily: _kFontFam);
}
